# Generated by Django 2.1.7 on 2019-03-24 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsfmember',
            name='place_of_birth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smsf_member_place_of_birth', to='smsf.Address'),
        ),
        migrations.AlterField(
            model_name='smsfmember',
            name='place_of_residence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smsf_member_place_of_residence', to='smsf.Address'),
        ),
    ]
