# Generated by Django 2.1.7 on 2019-05-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsfmember',
            name='lead_status',
            field=models.CharField(choices=[('1', 'New lead'), ('2', 'Contact attempted'), ('3', 'In progress'), ('4', 'Converted'), ('5', 'Abandoned')], default='1', max_length=1),
        ),
    ]
